### PR TITLE
Black format on lint

### PR DESCRIPTION
**Pull request by posix4e**
Soundtrack of this PR: [link to song that really fits the mood of this PR]()

### Motivation

Python deserves some linting, just like rust!

### In this PR
* I added black to the dockerfile
* I added black check to the linter tool
* I black formatted all linted python

### Future Work
* Potentially use  mypy for further checks
* perhaps move from pip3 black to apt

### CODE REVIEW

**Comment by posix4e** [comment]
Hey everyone should be good to go

**Review by jcape — APPROVED** [review]
Cleanup looks good to me, we should add black to the pre-commit hooks as well.

**Comment by posix4e** [comment]
@jcape that is your prerogative but I’d advise against it as you won’t be able to push to a local branch without linting.

**Comment by jcape** [comment]
No PR without linting will be accepted, so...?

**Comment by posix4e** [comment]
@jcape sorry for my previous terseness. I wasn't clear. My point was, often when it's late at night, I commit locally just so I don't lose my changes. This is a pain if we have a pre-commit hook. Also when I travel, I usually push to my fork even when it's a work in progress. Hence I don't like pre-push hooks. Totally your prerogative. I can see it both ways and welcome whatever way you wanna handle it.

**Comment by posix4e** [comment]
I’m worried this needs to be redone?

**Comment by lovetruthrespectlife** [comment]
https://www.instagram.com/lovetruthrespectlife/

**Comment by SmileyChris** [comment]
Just checked against latest black version and everything still looks good. The only addition is that black can handle `ipynb` files now, so one more file gets formatted:
```
$ black --version
black, 21.12b0 (compiled: no)

$ black . mob
reformatted mobilecoind/clients/python/jupyter/wallet.ipynb
All done! ✨ 🍰 ✨
1 file reformatted, 16 files left unchanged.
```

**Comment by remoun** [comment]
This PR still seems useful; do we want to merge or close it?

**Comment by SmileyChris** [comment]
(I would have said merge, not close...)

**Pull request closed without merging**
