### PR TITLE
Search-replace 2018-2021 with 2018-2022

### PR DESCRIPTION
**Pull request by eranrund**
`s/2018-2021/2018-2022/g`

### CODE REVIEW

**Review by zabrador — APPROVED** [review]
I spied some lints in there but they all seemed to be exclusively in comments, looks good!

**Review by garbageslam — APPROVED** [review]

**Review by nick-mobilecoin — APPROVED** [review]
This is outside the scope of this change, but has there been any discussion on standardizing the copyright format?
It looks like there are 4 versions:
* `Copyright 2018-2022 MobileCoin, Inc.`
* `Copyright (c) 2018-2022 The MobileCoin Foundation`
* `Copyright 2018-2022 The MobileCoin Foundation`
* `Copyright (c) 2018-2022 MobileCoin Inc.`

**Comment by nick-mobilecoin** [comment]
Looks like `fog/api/src/report_parse.rs` got missed

**Review by nick-mobilecoin — CHANGES_REQUESTED** [review]
Looks like fog/api/src/report_parse.rs got missed

**Comment by jcape** [comment]
> This is outside the scope of this change, but has there been any discussion on standardizing the copyright format? It looks like there are 4 versions:

Everything should be `Copyright (c) 2018-2022 The MobileCoin Foundation`.

**Review by nick-mobilecoin — APPROVED** [review]

**Pull request merged**
