### PR TITLE
release/v2: [Fixes] CI/CD, chart, container - Fix consensus node bootstrap from scratch. 

### PR DESCRIPTION
**Pull request by jgreat**
### Motivation

Fix the ability to bootstrap the network from scratch with a 2.x+ version container and charts. Useful for load testing.

- Add optional secrets for initial and fog keys seeds.
- Add MC_START_FROM=zero logic to ledger-distribution.

### CODE REVIEW

**Review by sugargoat — APPROVED** [review]
TY!

**Review by nick-mobilecoin — APPROVED** [review]

**Review by joekottke — CHANGES_REQUESTED** [review]
Looks like some Rust code snuck into this PR, is that intended?

**Comment by jgreat** [comment]
> Looks like some Rust code snuck into this PR, is that intended?

Seems linting/formatting didn't happen on one of the previous PRs, so unfortunately its necessary.

**Review by joekottke — APPROVED** [review]
LGTM

**Review by wjuan-mob — APPROVED** [review]

**Pull request merged**
