### PR TITLE
Libmobilecoin M1 fixes

### PR DESCRIPTION
**Pull request by eranrund**
### Motivation

We want to build `libmobilecoin` for the new M1 targets.

### In this PR
* Bump version of `cc` crate because we need https://github.com/alexcrichton/cc-rs/commit/178fd031e74f643721605e25110ee6abce8dbe05
* Add new targets and stop using `lipo` in `libmobilecoin/Makefile`

Note that currently the build only works for all targets on an Intel Mac. `x86_64-apple-ios` and `x86_64-apple-darwin` fail on an M1 due to weird linker issues.

### Future Work
* Make all targets buildable on an M1 mac

### CODE REVIEW

**Review by jcape — APPROVED** [review]

**Comment by the-real-adammork** [comment]
Im getting a compile error on my M1 Mac. Are there extra configuration steps that I need  ? 

Image 9-7-21 at 10 41 PM

**Comment by eranrund** [comment]
Which target are you trying to build?

**Comment by the-real-adammork** [comment]
It fails on the first target `aarch64-apple-ios-sim` this is the output I see in my terminal:

[build_output.txt](https://github.com/mobilecoinfoundation/mobilecoin/files/7132037/build_output.txt)

**Comment by eranrund** [comment]
That targets successfully builds on my M1. I have no idea what's missing on yours.
This Mac is running Big Sur 11.5.2 and has XCode 12.5.1 installed. It also has the following brew packages installed:
```
binutils 2.37
cmake 3.21.1
gdbm 1.20
gettext 0.21
git 2.32.0_1
go 1.16.6
llvm 12.0.1
mpdecimal 2.5.1
ncurses 6.2
openssl@1.1 1.1.1k
pcre 8.45
pcre2 10.37_1
protobuf 3.17.3
python@3.9 3.9.6
readline 8.1
six 1.16.0_1
sqlite 3.36.0
the_silver_searcher 2.2.0
xz 5.2.5
zsh 5.8_1
```

**Comment by eranrund** [comment]
This does remind me that I think there's a separate issue with `bindgen` that required me manually editing auto-generated code (the error is something about `va_list` missing, so different than what you're running into). I'll see if I can reproduce it and find a better workaround.

**Comment by the-real-adammork** [comment]
@eranrund ok I will configure my machine to match those brew settings and let you know if it works.

**Review by jcape — APPROVED** [review]

**Review by the-real-adammork — APPROVED** [review]
Tested on intel and working as expected. 🙏  eran

**Pull request merged**
