### PR TITLE
Use `ConfigSvn` from `mc-sgx-core-types`

### PR DESCRIPTION
**Pull request by nick-mobilecoin**
Previously there was a `ConfigSecurityVersion` defined in
`mc-attest-core`. Now the `ConfigSvn` from `mc-sgx-core-types` is used.

### CODE REVIEW

**Comment by nick-mobilecoin** [comment]
Current dependencies on/for this PR:
* master
  * **PR #3434** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/mobilecoin/3434" target="_blank">Graphite</a> 
    * **PR #3435** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/mobilecoin/3435" target="_blank">Graphite</a> 
      * **PR #3438** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/mobilecoin/3438" target="_blank">Graphite</a> 
        * **PR #3439** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/mobilecoin/3439" target="_blank">Graphite</a> 
          * **PR #3440** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/mobilecoin/3440" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/mobilecoinfoundation/mobilecoin/3440?utm_source=stack-comment).

**Review by dolanbernard — APPROVED** [review]

**Review by eranrund — APPROVED** [review]

**Comment by nick-mobilecoin** [comment]
@nick-mobilecoin started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/mobilecoinfoundation/mobilecoin/3440).

**Comment by nick-mobilecoin** [comment]
[Graphite](https://app.graphite.dev/github/pr/mobilecoinfoundation/mobilecoin/3440) rebased this pull request as part of a merge.

**Comment by nick-mobilecoin** [comment]
@nick-mobilecoin merged this pull request with [Graphite](https://app.graphite.dev/github/pr/mobilecoinfoundation/mobilecoin/3440).

**Pull request merged**
