### PR TITLE
[TOB-5] move FeeMap into mc-transaction-core so it could get used inside the transaction builder

### PR DESCRIPTION
**Pull request by eranrund**
We'd like to add a digest of the minimum `FeeMap` into the `Tx` struct,
and have `TransactionBuilder` include that in transactions it is
constructing (when the information is available).

The reason for this is explained in #2670. The stack of PRs that starts
with this one is an alternative approach that requires less changes in
clients since it is fully backwards compatible (excluding the digest
result in skipping the verificaiton, which is the current behavior).
More details are provided in the followup PR.

This particular PR is just a chore to reduce the changeset size - it
moves `FeeMap` into `mc-transaction-core`, knowing that it will need to
get used inside `TransactionBuilder` and we don't want that depending on
`mc-consensus-enclave-api`.

It is possible that `-core` is not the right place for this and instead
it should go into `mc-transaction-types` instead. I am open to moving
it, and have no strong preferences about this.

### CODE REVIEW

**Comment by eranrund** [comment]
Current dependencies on/for this PR:
* master
  * **PR #2792** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/mobilecoin/2792" target="_blank">Graphite</a>  👈
    * **PR #2793** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/mobilecoin/2793" target="_blank">Graphite</a> 
      * **PR #2794** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/mobilecoin/2794" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/mobilecoinfoundation/mobilecoin/2792?utm_source=stack-comment).

**Comment by garbageslam** [comment]
This is pulling into transaction-core a type that fundamentally needs an allocator, but this is somewhat at odds with a bunch of the hardware wallets work, which has duplicated a whole bunch of types in transaction core in order to avoid the allocator requirement. That stuff will eventually need to get reconciled with transaction core, perhaps by using heapless vec instead of vec in the transaction-core structures?

I wonder if we should not put the fee-map somewhere else, like a new crate. Is it needed for transaction validation? If not then maybe it doesn't need to be in transaction-core?

**Comment by eranrund** [comment]
> This is pulling into transaction-core a type that fundamentally needs an allocator, but this is somewhat at odds with a bunch of the hardware wallets work, which has duplicated a whole bunch of types in transaction core in order to avoid the allocator requirement. That stuff will eventually need to get reconciled with transaction core, perhaps by using heapless vec instead of vec in the transaction-core structures.
> 
> I wonder if we should not put the fee-map somewhere else, like a new crate. Is it needed for transaction validation? If not then maybe it doesn't need to be in transaction-core?
> 
> Otherwise, do you see a long term plan for how this could be done without requiring alloc? If there's no plan then we would probably just have to move it to a new crate in the future, so maybe we can cut to the chase? If there's a reasonable plan then maybe this is fine as is.

It doesn't need to be in `mc-transaction-core` but it does need to be usable in the enclave. So yes, it can go in its own crate or go into `mc-transaction-extra` but that means adding that to the enclave.

**Comment by garbageslam** [comment]
I guess I'm not going to block the PR on the issue but I'd appreciate if we think through whether its better to put this in its own crate. It's not a big deal to move it later though.

**Review by garbageslam — APPROVED** [review]

**Comment by eranrund** [comment]
> I guess I'm not going to block the PR on the issue but I'd appreciate if we think through whether its better to put this in its own crate. It's not a big deal to move it later though.

Cool. I am happy to move it to its own crate, or wait for https://github.com/mobilecoinfoundation/mobilecoin/pull/2810 to land and then switch to that.

**Review by nick-mobilecoin — APPROVED** [review]

**Review by remoun — APPROVED** [review]

**Pull request merged**
