### PR TITLE
Fix peer flag accepting mcp URLs

### LINKED ISSUE #828: mobilecoind should reject `mcp://` URLs
As discussed in #827, mobilecoind allows the user to specify `mcp://` URLs for peers, which validator nodes rightly reject. This should never be the case.

### PR DESCRIPTION
**Pull request by remoun**
Fixes #828: `--peer` accepts `mcp://` URLs.

### CODE REVIEW

**Review by jcape — APPROVED** [review]
Thanks!

**Review by zabrador — COMMENTED** [review]
I'm curious if anyone else sees those `Cargo.lock` changes in their local environment, otherwise this looks good to me!

**Comment by remoun** [comment]
> I'm curious if anyone else sees those `Cargo.lock` changes in their local environment, otherwise this looks good to me!

I think this is due to the recent dependabot PRs. Doing a clean build on `master` yields the same changes to `Cargo.lock`. It also shows up in recent dependabot PRs, e.g. https://github.com/mobilecoinfoundation/mobilecoin/pull/1323

**Review by garbageslam — APPROVED** [review]
LGTM

**Pull request merged**
