### PR TITLE
API for get membership proofs of UnspentTxOut list

### PR DESCRIPTION
**Pull request by jadeydi**

### CODE REVIEW

**Comment by ericmeltzer** [comment]
hi @sugargoat @posix4e @garbageslam et al~ this PR comes from the https://github.com/MixinNetwork folks who are getting ready to bring mobilecoin transfers live in their app—review appreciated :)

**Comment by posix4e** [comment]
Can we get a test?

**Comment by eranrund** [comment]
@jadeydi thank you for submitting this PR. I have added a unit test for this. I believe that once CI is green we will be able to move forward with merging it.

**Review by sugargoat — APPROVED** [review]

**Review by eranrund — APPROVED** [review]

**Comment by jadeydi** [comment]
> @jadeydi thank you for submitting this PR. I have added a unit test for this. I believe that once CI is green we will be able to move forward with merging it.

Thanks eranrund

**Pull request merged**
