### PR TITLE
Use `FamilyId` from `mc-sgx-core-types`

### PR DESCRIPTION
**Pull request by nick-mobilecoin**
Previouisly the `FamilyId` was defined in `mc-attest-core`. Now the
`FamilyId` from `mc-sgx-core-types` is used.

### CODE REVIEW

**Comment by nick-mobilecoin** [comment]
Current dependencies on/for this PR:
* master
  * **PR #3434** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/mobilecoin/3434" target="_blank">Graphite</a> 
    * **PR #3435** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/mobilecoin/3435" target="_blank">Graphite</a> 
      * **PR #3438** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/mobilecoin/3438" target="_blank">Graphite</a> 
        * **PR #3439** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/mobilecoin/3439" target="_blank">Graphite</a> 
          * **PR #3440** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/mobilecoin/3440" target="_blank">Graphite</a> 
            * **PR #3441** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/mobilecoin/3441" target="_blank">Graphite</a> 
              * **PR #3442** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/mobilecoin/3442" target="_blank">Graphite</a> 
                * **PR #3443** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/mobilecoin/3443" target="_blank">Graphite</a> 
                  * **PR #3444** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/mobilecoin/3444" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/mobilecoinfoundation/mobilecoin/3444?utm_source=stack-comment).

**Review by eranrund — APPROVED** [review]
LGTM aside from the `Ord` stuff that has already been mentioned in similar PRs

**Comment by nick-mobilecoin** [comment]
@nick-mobilecoin started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/mobilecoinfoundation/mobilecoin/3444).

**Comment by nick-mobilecoin** [comment]
[Graphite](https://app.graphite.dev/github/pr/mobilecoinfoundation/mobilecoin/3444) couldn't merge this pull request because a downstack PR #3442 failed to merge.

**Comment by nick-mobilecoin** [comment]
@nick-mobilecoin started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/mobilecoinfoundation/mobilecoin/3444).

**Comment by nick-mobilecoin** [comment]
[Graphite](https://app.graphite.dev/github/pr/mobilecoinfoundation/mobilecoin/3444) rebased this pull request as part of a merge.

**Comment by nick-mobilecoin** [comment]
@nick-mobilecoin merged this pull request with [Graphite](https://app.graphite.dev/github/pr/mobilecoinfoundation/mobilecoin/3444).

**Pull request merged**
