### PR TITLE
Add verification of Debug bit off for release enclaves

### PR DESCRIPTION
**Pull request by nick-mobilecoin**
When an enclave is built for debug, a bit is set in the `Attributes`.
The DCAP verifier now checks for this bit being set when it shouldn't
be.

### CODE REVIEW

**Comment by nick-mobilecoin** [comment]
Current dependencies on/for this PR:
* master
  * **PR #3508** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/mobilecoin/3508" target="_blank">Graphite</a> 
    * **PR #3509** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/mobilecoin/3509" target="_blank">Graphite</a> 
      * **PR #3510** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/mobilecoin/3510" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/mobilecoinfoundation/mobilecoin/3510?utm_source=stack-comment).

**Review by eranrund — APPROVED** [review]

**Comment by nick-mobilecoin** [comment]
@nick-mobilecoin started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/mobilecoinfoundation/mobilecoin/3510).

**Comment by nick-mobilecoin** [comment]
[Graphite](https://app.graphite.dev/github/pr/mobilecoinfoundation/mobilecoin/3510) rebased this pull request as part of a merge.

**Comment by nick-mobilecoin** [comment]
@nick-mobilecoin merged this pull request with [Graphite](https://app.graphite.dev/github/pr/mobilecoinfoundation/mobilecoin/3510).

**Pull request merged**
