### PR TITLE
Allow passing extra GRPC services to AdminServer

### PR DESCRIPTION
**Pull request by eranrund**
### Motivation

A bunch of our applications already include this internal, privileged GRPC server, and it could be convenient to use it for extra app-specific functionality.

Specifically, I want to add some admin commands to the DEQS liquidity bot, and it already has this GRPC server, so it seemed like the right place for it, but at the moment there's no way to add extra GRPC services so I either copy-paste `AdminServer`, or we extend it to allow passing of extra GRPC services.

### CODE REVIEW

**Comment by cbeck88** [comment]
If you want this for deqs repo, are you going to bump deqs repo to point at master?
I thought we have it on 4.1 for compatibility

**Comment by eranrund** [comment]
> If you want this for deqs repo, are you going to bump deqs repo to point at master? I thought we have it on 4.1 for compatibility

Oops yeah this should be against `release/v4.1`, thanks

**Review by cbeck88 — APPROVED** [review]
seems fine to me

**Comment by jcape** [comment]
This should be pointed at master: we haven't done any testing on this at all, it wasn't brought up in any meeting, and we're releasing in < 6 hours.

5.0 is (tentatively) scheduled for release on Monday, there's literally zero point to put this into the stable branch at this late a stage.

**Review by jcape — CHANGES_REQUESTED** [review]
It's too late to add new features to 4.1.

**Comment by cbeck88** [comment]
Maybe we can do a 4.1+dev branch for the deqs so that we arent building against master for prod?

**Comment by eranrund** [comment]
I don't remember whats getting into 5.0 but maybe we can just move the DEQS to point at 5?

**Comment by jcape** [comment]
The current plan is for `master` to become `release/v5.0` next week, and it will include dependency updates, more work on hardware wallet support, and the fog view and ledger routers.

`release/v4.1` is being released today. We have an our set aside every week to discuss what goes into what releases and what the timelines are, and we've already pushed `release/v4.1` back several times.

**Comment by cbeck88** [comment]
Im not asking to push back `release/v4.1` -- lets chat offline

**Review by jcape — APPROVED** [review]

**Pull request merged**
