### PR TITLE
Add key utility

### PR DESCRIPTION
**Pull request by sugargoat**
### Motivation

Simple python utility for reformatting account key contents.

### In this PR
* Adds key-util.py

### CODE REVIEW

**Review by eranrund — COMMENTED** [review]
I don't think it needs to be in its own directory, and `mobilecoind/clients` is an odd place for it. How about `https://github.com/mobilecoinofficial/mobilecoin/tree/master/tools`?
Additionally, `key-util` is not a descriptive name. Maybe `entropy2hex.py`?
I also think it can just output to stdout, and you could redirect it into a file if you wanted to but I don't feel strongly about any of this.

**Comment by rjwalters** [comment]
seems like `scratchpad` might be a better fit?

**Comment by sugargoat** [comment]
Could be scratchpad - it's part of the offline transaction flow, so it should be in this repo if I add documentation that explicitly walks through offline transactions. I should add that documentation anyway, will do as part of this PR, and move it to tools in the meantime.

**Comment by sugargoat** [comment]
Not needed at this time - can be reopened if we need the utility again.

**Pull request closed without merging**
