### PR TITLE
release/v3.0 - CI/CD - CD on PR

### PR DESCRIPTION
**Pull request by jgreat**
### Motivation
Make sure that CD is run when we have a PR to master or release/ branches. Skip CI/CD when changes are only to .md files.

### When to require CI/CD runs:

- PR to master
- PR to release/

### Opt into CD:

- create a branch with feature/

How to opt out of CI/CD runs:

- add the GHA built in [skip ci] to your commit message.

Changes:
- on.pull_request CD workflow
- move all CD dispatch calls to workflow calls.
- clean up steps that described the workflow calls.
- Add human names to the manual dispatch calls.
- make testing workflow line up with current master.
- remove CD debugging skip filters for now.
- update docker actions to remove deprecated nodejs version warnings
- update metadata to remove deprecated GHA set-output calls

Future Work:
- add more file exclusions
- Add logic to skip just CD or just CI.

### CODE REVIEW

**Review by garbageslam — CHANGES_REQUESTED** [review]
I think this is a bad change to merge right now, and it's going to blow up the dev cluster.

If we do this, then every dependabot PR (which opens against master), will create it's own network, in order to do CD on that PR.

This will consume all of the cluster resources and prevent us from testing our actual work.

Without a fix for this issue I don't think we can merge this change.

**Comment by jgreat** [comment]
@garbageslam This change deletes the PR CD run environment once it completes successfully.  So if its successful it won't consume dev cluster resources.

This also does a bunch of clean up on the workflow and lays the foundation for working on optimizing the CD going forward.  It changes the workflow so its not doing the hacky dispatch calls now that GHA fully supports the more direct workflow_calls.

**Review by eranrund — APPROVED** [review]

**Comment by eranrund** [comment]
> I think this is a bad change to merge right now, and it's going to blow up the dev cluster.
> 
> If we do this, then every dependabot PR (which opens against master), will create it's own network, in order to do CD on that PR.
> 
> This will consume all of the cluster resources and prevent us from testing our actual work.
> 
> Without a fix for this issue I don't think we can merge this change.
> 
> I think it's okay to separate the release/v3.0 part from the master part, and solve the issue for master later.

I thought the idea is that the workflow itself will decide on whether to proceed based on the branch name?

**Comment by garbageslam** [comment]
@jgreat i think currently dependabot opens as many as 12 PRs at once typically and the configured limit is like 25. But it seems that once we have 5 or 6 concurrent networks, they all start failing?

If we also reduce dependabot limits to like 2 or 3, so they happen in the middle of the night and are then deleted, it might be okay? Can we do that dependabot change in this PR?

**Comment by garbageslam** [comment]
Sorry i guess i got confused, this is the release v3 PR and i meant to comment on the master version

**Review by garbageslam — APPROVED** [review]

**Comment by jgreat** [comment]
We will need to keep dependabot from running on the CD anyways, because it opens the PRs as a foreign actor.  Those PRs do not get access to secrets so the actions wouldn't be able to deploy to the cluster. 

Its weird that the CI runs automatically,  fork PRs from non-members are supposed to require approval to run actions.

**Comment by garbageslam** [comment]
I think dependabot PRs arent fork PRs, we add the dependabot integration to our org and the PR branches come down to my machine when I pull origin, so they are similar to engineer-created PRs

**Review by eranrund — APPROVED** [review]

**Review by joekottke — APPROVED** [review]
Really like the friendly display names

**Pull request merged**
