### PR TITLE
Add Quote3 verifier

### PR DESCRIPTION
**Pull request by nick-mobilecoin**
Initial implementation of a Quote3 verifier. Currently this is only a
wrapper around the `mc-attestation-verifier::EvidenceVerifier`. In the
future it will be expanded to support more of the MobileCoin repo specific use
case.

### CODE REVIEW

**Comment by nick-mobilecoin** [comment]
Current dependencies on/for this PR:
* master
  * **PR #3495** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/mobilecoin/3495" target="_blank">Graphite</a> 
    * **PR #3496** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/mobilecoin/3496" target="_blank">Graphite</a> 
      * **PR #3497** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/mobilecoin/3497" target="_blank">Graphite</a> 
        * **PR #3503** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/mobilecoin/3503" target="_blank">Graphite</a> 
          * **PR #3504** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/mobilecoin/3504" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/mobilecoinfoundation/mobilecoin/3504?utm_source=stack-comment).

**Review by eranrund — APPROVED** [review]

**Comment by nick-mobilecoin** [comment]
@nick-mobilecoin started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/mobilecoinfoundation/mobilecoin/3504).

**Comment by nick-mobilecoin** [comment]
[Graphite](https://app.graphite.dev/github/pr/mobilecoinfoundation/mobilecoin/3504) rebased this pull request as part of a merge.

**Comment by nick-mobilecoin** [comment]
@nick-mobilecoin merged this pull request with [Graphite](https://app.graphite.dev/github/pr/mobilecoinfoundation/mobilecoin/3504).

**Pull request merged**
