### PR TITLE
chore(deps): Update go-grpc-gateway to use go 1.19, newer dependencies

### PR DESCRIPTION
**Pull request by jcape**
- Replace github.com/mobilecoinofficial/grpc-proxy with github.com/mobilecoinfoundation/mobilecoin/go-grpc-gateway
- Run go mod tidy to cleanup go.mod
- Upgrade dependencies with go get -u

### Motivation

We previously hadn't updated anything about the go-grpc-gateway, this catches things up to the current latest revisions of things.

### CODE REVIEW

**Comment by jcape** [comment]
Current dependencies on/for this PR:
* release/v4.1
  * **PR #3162** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/mobilecoin/3162" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/mobilecoinfoundation/mobilecoin/3162?utm_source=stack-comment).

**Comment by cbeck88** [comment]
i think if we change the name of the module the name of the binary artifact gets changed, we might need to update some of this:

```
$ git grep "grpc-proxy"
.github/workflows/mobilecoin-dev-cd.yaml:        cp grpc-proxy ../go_build_artifacts/
.internal-ci/docker/Dockerfile.go-grpc-gateway:COPY ${GO_BIN_PATH}/grpc-proxy /usr/bin/go-grpc-gateway
.internal-ci/util/manual_republish_existing_build.sh:    docker cp "go-grpc-gateway:/usr/bin/go-grpc-gateway" ./grpc-proxy
go-grpc-gateway/.gitignore:grpc-proxy
go-grpc-gateway/go.mod:module github.com/mobilecoinofficial/grpc-proxy
go-grpc-gateway/main.go:        gw "github.com/mobilecoinofficial/grpc-proxy/gen"
go-grpc-gateway/test.sh:if [ ! -f "grpc-proxy" ]; then
go-grpc-gateway/test.sh:    echo "Missing grpc-proxy, needs go build"
go-grpc-gateway/test.sh:./grpc-proxy -grpc-insecure -grpc-server-endpoint localhost:3000 -http-server-listen :8080 -logtostderr &
```

it looks like in the Dockerfile.go, jason was already renaming `grpc-proxy` to `/usr/bin/go-grpc-gateway` ?
I think that one of the `.github/` or `.internal-ci/docker` lines is probably the `cp` that's failing in the most recent CD log

**Comment by cbeck88** [comment]
we might need to update release scripts also?

**Comment by cbeck88** [comment]
this looks good to me, we passed the go tests, and the CD failure looks spurious

**Review by cbeck88 — APPROVED** [review]

**Review by nick-mobilecoin — APPROVED** [review]

**Pull request merged**
