### PR TITLE
Group enclave and base dirs together, add reviewers.

### PR DESCRIPTION
**Pull request by jcape**
This PR is attempting to coerce dependabot into updating multiple cargo workspaces/lock files in a single PR. We'll see how well it goes...

### CODE REVIEW

**Review by eranrund — APPROVED** [review]
Nice (if it works :))

**Comment by jcape** [comment]
Unfortunately it looks like it won't work: https://github.com/dependabot/dependabot-core/issues/2824

**Comment by jcape** [comment]
https://github.com/dependabot/dependabot-core/issues/2178 is the issue to fix it, but it's just a bunch of plus-ones at this point.

**Comment by jcape** [comment]
Just going to close this, the best option is simply to triage the PRs as they come in.

**Pull request closed without merging**
