### PR TITLE
Rust Nightly Update

### PR DESCRIPTION
**Pull request by jcape**
### Motivation

In order to effectively support M1, as well as keep our own dependencies up to date, we would like to update the version of rust which we are using. This PR accomplishes that goal.

### In this PR
* Update rust to `nightly-2021-07-21`
* Updates rust-mbedtls fork to remove `core_io`
* Handle removal of `feature(external_doc)`
* Handle removal of `core::raw` (specifically `TraitObject`)
* Fix clippy warnings.
* Fork `bulletproofs`, `datatest`, `ed25519-dalek`, `x25519-dalek`, `schnorrkel` to handle changes.

### Future Work
* Get PRs for forks merged into upstream repos

### CODE REVIEW

**Comment by garbageslam** [comment]
changes in `mc-sgx-panic` all look good to me

**Review by christian-oudard — APPROVED** [review]

**Review by garbageslam — APPROVED** [review]
LGTM thank you!

**Review by eranrund — COMMENTED** [review]
LGTM as far as I can tell. Has this been deployed and Grafana looked at?

**Comment by jcape** [comment]
> 
> 
> LGTM as far as I can tell. Has this been deployed and Grafana looked at?

Not yet, pushing to build network now

**Comment by jcape** [comment]
Master 2021-07-03T17:30:
Screenshot from 2021-09-07 14-46-19

PR:
Screenshot from 2021-09-07 14-46-48

There is a large spike of "task_msgs" messages for node1 at 14:08:00-14:08:30 in the PR, and a corresponding one for node1 at 17:31:30 in the master graph (i.e. I believe the slight decrease in tps is attributable to transitory queing showing up earlier in the submission during the PR---worth investigating further, but I don't think there's any fundamental performance difference between March and July Rust.)

**Pull request merged**
