### PR TITLE
Add jitter to most retry iterators

### PR DESCRIPTION
**Pull request by remoun**
### Motivation

When we have multiple instances of a program that includes retries, there is a risk of having many retries synchronize, creating a kind of thundering herd problem when attempting to recover from transient errors. 

### In this PR
* Add a `.map(delay::jitter)` call to all call sites that create a delay iterator for `retry` calls with a remote connection.

### CODE REVIEW

**Review by eranrund — APPROVED** [review]

**Review by jcape — COMMENTED** [review]
Am I reading this correctly? Does this mean it could be `secs * (0..f64::MAX)`?
```
/// Apply full random jitter to a duration. (need `random` feature)
pub fn jitter(duration: Duration) -> Duration {
    let jitter = random::<f64>();
    let secs = ((duration.as_secs() as f64) * jitter).ceil() as u64;
    let nanos = ((f64::from(duration.subsec_nanos())) * jitter).ceil() as u32;
    Duration::new(secs, nanos)
}
```

**Comment by remoun** [comment]
> Am I reading this correctly? Does this mean it could be `secs * (0..f64::MAX)`?

Fair question! The[`random` docs](https://docs.rs/rand/latest/rand/fn.random.html) state "Floating point types (f32 and f64): Uniformly distributed in the half-open range [0, 1)"

**Comment by garbageslam** [comment]
@james I think the docu says, `random::<f64>()` is in the range (0,1): https://rust-random.github.io/rand/rand/fn.random.html

**Review by jcape — APPROVED** [review]

**Comment by jcape** [comment]
LGTM, then :-)

**Pull request merged**
